# https://docs.travis-ci.com/user/docker/
sudo: required
language: ruby
services:
  - docker

before_install:
  - gem install blog-generator

script:
  - rake build

after_success:
  - test "$TRAVIS_BRANCH" == "master" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - test "$TRAVIS_BRANCH" == "master" && docker push docker push botanicus/botanicus.me
