sudo: required

services:
  - docker

script:
  - rake build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push docker push botanicus/botanicus.me;
    fi
