# https://docs.travis-ci.com/user/docker/
sudo: required
language: ruby
services:
  - docker

before_install:
  # http://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset
  - npm config set registry http://registry.npmjs.org/

install:
  - gem install blog-generator

script:
  - blog-generator.rb generate api.botanicus.me # This has to run before we test the blog, remember my-story is required.
  - cd blog.botanicus.me && npm install && npm test; cd -
  - cd blog.botanicus.me && npm run build; cd -
  - rake docker:build

after_success:
  - test "$TRAVIS_BRANCH" == "master" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - test "$TRAVIS_BRANCH" == "master" && rake docker:push
